### ISSUE TITLE
Imu plugin: gravity error?

### ISSUE THREAD

**Issue by costashatz** [tu-darmstadt-ros-pkg/hector_gazebo#11] opened 2014-05-29 12:59 UTC
I have seen in the code you subtract the gravity from link/body's acceleration. This seems like an error (in RVIZ IMU measurements point upwards) as the gravity returned by gazebo already has the minus sign.

Is this done for some specific reason (different purpose IMU sensor?)?

Best,
Konstantinos

**Comment by meyerj** [comment] 2014-06-02 08:16
This is a duplicate of #8.

It is a matter of sign convention. If the sensor plugin would directly output the acceleration of the probe mass, you would have to add the gravity vector. But the sensor signal represents the acceleration of the body/robot the sensor is attached to, which has an inverted sign and can be directly integrated to a velocity - once the gravity is compensated.

**Closed as completed by meyerj** 2014-06-02 08:16 UTC

**Comment by costashatz** [comment] 2014-06-02 21:38
Thanks for the explanation..
